spring.application.name=mongodbConnect
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017}
spring.data.mongodb.database=${MONGODB_DATABASE:mongodbConnect}

spring.threads.virtual.enabled=true
